version: '3.9'

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    image: kagemeka/create-lambda-layer:python
    
    volumes:
      - type: bind
        source: .
        target: /tmp
    

    command: [
      /tmp/,
    ]

    